### ISSUE TITLE
Get obj or svg of panels "stitched" together

### ISSUE THREAD

**Issue by rahul-mitra13** [maria-korosteleva/Garment-Pattern-Generator#11]
Hello, 

Thank you for releasing this public dataset! :) 

My question is perhaps related #1. Let's say I just want to stitch specific panels (eg. front) of a garment together using the connectivity information from the spec file and store the result in an svg or obj file. Is there any place in your pipeline to access this information in a principled manner? Right now, I'm using the spec file to manually stitch together the panels in Blender but it requires a lot manual editing which makes my meshes quite unstructured, which will cause problems for downstream applications. 

Was curious if there was any place I could access these stitched panels together from? Congrats on this project! Any help or pointers would be appreciated!

**Comment by maria-korosteleva** [comment]
Hi @rahul-mitra13 
I'm happy that you find our work useful =) As for your question:

1) Unfortunately, svg format does not allow connectivity specification (as far as I know)

2) However, you can easily save a boxmesh as an OBJ file, which contains the stitched meshed panels and is used as a starting point of the simulation. Here is what it looks like: 
![image](https://github.com/maria-korosteleva/Garment-Pattern-Generator/assets/6837635/9827fcac-0d0f-4c51-b4cb-6834924c449f)

To save it, you can simply run garment.save_mesh() before the start of the sim, e.g. by uncommenting this line: https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/6b44100aeee3105709e434364b1a90bd1dea006e/packages/mayaqltools/simulation.py#L221

3) All the meshes in the data have UV coordinates (texture coordinates in OBJ format) that are grouped by panels. You can use these coordinates to recover the default lengths of mesh edges, if this information is required by your simulation setup

**Comment by rahul-mitra13** [comment]
Thanks for your helpful response! 

What I really need for my application is consistency across stitch edges. For example, if I compute a function over the edges in the front panel, it should get propagated to the mapped edges in the back panel.  The boxmesh you have is a good starting point since there seems to be a 1-to-1 mapping between vertices/edges on the front panel to vertices/edges on the back panel. Is there a quick way to query this eventual mapping without generating the entire boxmesh in Maya? Looking forward to hearing from you!

**Comment by maria-korosteleva** [comment]
I'm not sure I correctly understand the question. If you require the mapping between the vertices and edges of the (eventual) mesh, then yes, you'd need to generate the boxmesh first, for which we use Maya and Qualoth tools in this project. 

If you require a mapping between the vertices and edges of the panels (as defined in a pattern spec), then the stitching information given in the spec should be enough. The only caveat is that the stitching direction of the pair of edges in a stitch is omitted (are you referring to this issue in your question?)

Some things to note: 
1) in the boxmesh and simulated meshes the mesh vertices and edges from connected panels are merged -- stitched panels share the edges on the stitched side. 
2) We provide the segmentation information that indicates which of the edges

**Comment by rahul-mitra13** [comment]
Thank you for your response and sorry if I'm not being clear. 

What I'm after is 2 global "stitched together" panels (one for the front and one for the back). And also, have the mapping information between vertices on the front panel to vertices on the back panel. 

To do this, I first convert all the svgs in a dataset to individual objs  and use boolean operations in Blender to manually stitch them up. Here is one I came up with for just the front panels of the sleeveless jumpsuit model. 

<img width="391" alt="Screenshot 2024-06-19 at 12 25 51 PM" src="https://github.com/maria-korosteleva/Garment-Pattern-Generator/assets/32472390/8d89ec66-11c0-479d-a92d-2a3a53450a80">

However, this required a lot of manual tweaking (scaling the size of the panels) and a few boolean operations to ensure that it was indeed one manifold obj. Also, you can see that the triangulation around the stitches gets really bad. I want to avoid these manual tweaks (since they will lead to downstream issues in my application) and was wondering if there is any place in your pipeline that did this stitching for a set of front (or back) panels. 

Based on your response, it seems as though you're using Maya and Qualoth tools to go from your custom json specification to these stitched together meshes with mapping info. I only need to extract a mesh like the one I have shown above (given a custom json specification), so I was curious if there's anywhere in your pipeline I could look to do this in a more principled manner (than the manual tweaking I'm doing now). 

Hope this clears things up a little bit. Any help or pointers would be appreciated! Happy to try and be a little more clear too. :)

**Comment by maria-korosteleva** [comment]
Okay, it's more clear now

1) So, yes, we are using Maya and Qualoth tools to generate the mesh, so unfortunately, the whole process relies on their implementation in this project. 
2) Secondly, we do not make distinction between panels or stitches, all the stitches (e.g. front of the top and front of the skirt, or front of the top to the back of the top) are treated the same. 

What might be helpful
1) You can control the order of stitching in Qualoth to separately stitch all the front panels and all the back panels, so that you can save "generalized front" and "generalized back" separately. This would need some modification of our pipeline code
2) In our new project, we are moving to open source implementation. The code is not yet available, but you can find the process of generating the mesh for patterns in the pre-print (https://arxiv.org/html/2405.17609v1). Maybe you will find some of the ideas useful.

P.S. Side note on your problem formulation, feel free to ignore if not relevant. In general case, pattern cannot be represented through flat front and back panels. E.g., in the jumpsuit example it's likely that the pant panels will overlap in the crotch area. The correct shape of the sleeve opening can only be stitched to bodice piece in 3D (requires fabric bending). Note that the sleeves in this projects are simplified compared to the normal ones. In multi-panel skirts (e.g. 4 & 8 in this dataset) the stitches are distributed to accentuate the design and may not align with the body sides, so you would need to make new cuts for front/back separation

**Comment by rahul-mitra13** [comment]
Got it, thanks for the responses! Yes, trying to manually write up something now that goes from these panels to stitches. I'll close the issue for now.

**Comment by rahul-mitra13** [comment]
Hello, 

I’m attempting to triangulate the panels using the vertices/connectivity information specified in the json files.  I wanted to ask about my interpretation of the curvature coordinates on an edge that specifies the control point of a quadratic Bézier curve. If it’s specified as “absolute”, it’s just another point in space. However, if it’s specified as “relative”, going off the docs, I assume the control point is specified as a simple linear interpolation between the endpoints of the edge treating the edge as a vector (1, 0). So for example, if my edge was give by p1,p2 (and directed from p1 to p2) and the curvature coordinates were given by t, then the control point is: 

p_control = t(p1) + (1- t) * p2

However, when I generate the vertices on the border of the panels and triangulate them, I get very different results when compared to the associated svgs provided. For example here is a picture of one of the svgs. 

<img width="187" alt="lfsleeve_png" src="https://github.com/maria-korosteleva/Garment-Pattern-Generator/assets/32472390/0d8a6cb8-eaa3-4b43-a825-fa57daf54542">



And here is the corresponding vertices I generate. I generate these vertices by sampling 10 vertices on every edge of the panel. Then to generate my mesh (internal triangles), I run a constrained Delaunay triangulation. 

<img width="1039" alt="lfsleeve" src="https://github.com/maria-korosteleva/Garment-Pattern-Generator/assets/32472390/897025ec-28ea-4fdf-ae28-7e988d558027">



Naturally, the triangulation comes out a little strange as well. You can clearly see that the curves in the svgs are a lot more aggressive than those produced by my triangulation. Just so I ensure that my implementation is correct, I had two questions: 

- Am I interpreting the curvature coordinates correctly?  
- How exactly were the svgs generated? As I mentioned, the Bézier curves in the svgs look a lot more aggressive than the ones I come up with. I’m trying to make these panels as accurate as possible to the input specification. 

This dataset is great and I really want to work with it. Please let me know if you have any thoughts and I look forward to hearing from you! Thanks! :)

**Comment by maria-korosteleva** [comment]
Hi @rahul-mitra13 

No, you are not interpreting the relative coordinates correctly. Curvature coordinates are given in a local coordinate system with respect to the edge. The start of the edge is the origin, Ox is aligned with the edge, and Oy is perpendicular, so all you need to do is to perform a coordinate transformation to go from relative to absolute and back. 

Here is the function for converting relative coordinates to absolute ones:
https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/6b44100aeee3105709e434364b1a90bd1dea006e/packages/pattern/core.py#L388

All the other code related to saving a pattern as SVG can be found here: 
https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/6b44100aeee3105709e434364b1a90bd1dea006e/packages/pattern/wrappers.py#L163

**Comment by rahul-mitra13** [comment]
Hello, 

Ah, gotcha. The panels look a lot better now! 

<img width="676" alt="Screenshot 2024-06-28 at 3 08 48 PM" src="https://github.com/maria-korosteleva/Garment-Pattern-Generator/assets/32472390/c48999d0-dc73-440f-8a5e-d77f88a285bf">

And I'm also able to store the vertex mappings across stitches. Thanks for all your help!

**Comment by maria-korosteleva** [comment]
Oh, great it worked out! I'm happy to help :)

**Comment by rahul-mitra13** [comment]
Hey! I just open-sourced the code [here](https://github.com/rahul-mitra13/GarmentCodeToObj) in case it's useful. :)

**Comment by maria-korosteleva** [comment]
Wonderful, thank you for sharing!

сб, 10 мая 2025 г. в 02:38, Rahul Mitra ***@***.***>:
