### ISSUE TITLE
About datasim.py

### ISSUE THREAD

**Issue by jingfengguo-ai** [maria-korosteleva/Garment-Pattern-Generator#12]
Hello, I now have a pred_specification.json file containing the sewing pattern information, how should I simulate to get the obj file of the garment, can you give me some suggestions on modifying the datasim.py file?

**Comment by maria-korosteleva** [comment]
Please, use [Garment viewer GUI](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/docs/Setting_up_generator.md#preview-your-setup-in-garmentviewer-gui) for loading and simulating individual patterns
