### ISSUE TITLE
How to normalize the body model

### ISSUE THREAD

**Issue by jingfengguo-ai** [maria-korosteleva/Garment-Pattern-Generator#15]
I use other body models, I would like to ask how I should normalize the body model so that the clothes fit on the body？

**Comment by jingfengguo-ai** [comment]
Hello, I have generated the clothes, but I want to use our own body model, I imported the spec and our body model into Maya to get this effect,  how do I normalize the body model to fit the generated clothing?

<img width="472" alt="企业微信截图_17332273824353" src="https://github.com/user-attachments/assets/d4d58b61-bc75-4e90-ac65-9f6838a7ffba">

**Comment by maria-korosteleva** [comment]
Hi @gjgjgjfff 

There are a few comments I can make about your request: 
1. All the 3D body models are expected to use meters or centimeters as base units. 
2. In this project, the 3D body models are expected to have the center of mass at the origin. 
3. All the garments are designed to fit the SMPL female average body model. Much like in real clothing, fit does not only include the overall scale but also considers the relative proportions of body parts. Garment retargeting between different body shapes is an open research problem, and this project does not support such retargeting

I recommend you to check out GarmentCode, where patterns are more flexible and can be fitted to various body shapes
https://github.com/maria-korosteleva/GarmentCode
