### ISSUE TITLE
How to filter failure case 

### ISSUE THREAD

**Issue by machffud** [maria-korosteleva/Garment-Pattern-Generator#16]
Dear @maria-korosteleva,

Thank you for another great project.
<img width="329" alt="image" src="https://github.com/user-attachments/assets/d15a6f51-1821-45cc-bfbe-843b622ff85f">
I would like to know how to exclude the failure cases from the current dataset that described on above image. Could you provide me with the list of instance IDs that are classified as failure cases?

I attempted to access the [Datasheet](https://zenodo.org/api/files/82d24e49-a652-46d2-9d9f-7197ec4addc5/Datasheet%20for%20Dataset%20of%203D%20Garments%20with%20Sewing%20Patterns%20v1..pdf?versionId=c27d0083-335f-4c0f-9c15-cc84361c1677) from [this link](https://zenodo.org/records/5267549), but I do not have access.

Thanks

**Comment by maria-korosteleva** [comment]
Dear @machffud,

The list of fails is available in dataset_properties.json files that can be found in each per-type folder
