### ISSUE TITLE
How to dress customer smplx model？

### ISSUE THREAD

**Issue by skeras** [maria-korosteleva/Garment-Pattern-Generator#2]
Hi，
  Thanks for your great project.
how to dress customer smplx model？

**Comment by maria-korosteleva** [comment]
Hi @skeras,  thanks for your kind words!

I think I need more context for your question. What are the differences between your customer smplx model and our default example (e.g. shape, pose, need to apply animations, etc.)?

Our default body model is SMPL average woman pose (which is the same for SMPL and SMPLx). Generally speaking, you can use any .obj file as a body model in our pipeline. For example, when using our garmentviewer GUI in Maya: https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/garmentviewer.py

**Comment by skeras** [comment]
Hi, 
   Thanks for your quick reply.
    SMPLX = SMPL + HAND +EXpression.  https://github.com/vchoutas/smplx
    I am comfused how to drape the garment to smpl body module?

**Comment by maria-korosteleva** [comment]
You have two options: 

1) You just need to drape one or a couple of examples. In this case, you need to run our [GUI in Autodesk Maya](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/garmentviewer.py). The instructions are given in the comments to the file. From GUI, you can choose any .obj file for the body model. Here is an [overview of GUI](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/docs/Setting_up_generator.md#preview-your-setup-in-garmentviewer-gui)

2) You are doing a simulation for a set of garment samples created by our sewing pattern generator (https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/datagenerator.py). In this case, 
   * you specify the name of the body model .obj file in [config file.](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/docs/Setting_up_generator.md#simulation-config-file). Examples of config files are [here](https://github.com/maria-korosteleva/Garment-Pattern-Generator/tree/master/data_generation/Sim_props) 
   * Path to the folder with body models should be specified in system.jsoin, please, see [Installation instructions ](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/docs/Installation.md#local-paths-setup)
   * => This will point the system to your desired body model. 
 
In either case, for SMPL, you can use the model that we provide [here](https://github.com/maria-korosteleva/Garment-Pattern-Generator/tree/master/data_generation/Bodies). 

Please, refer to our [docs](https://github.com/maria-korosteleva/Garment-Pattern-Generator/tree/master/docs) for more info on the system.
