### ISSUE TITLE
No module named 'pattern'

### ISSUE THREAD

**Issue by skeras** [maria-korosteleva/Garment-Pattern-Generator#3]
Hi, 
  When i run datagenerator.py get an error message "No module named 'pattern'", how to fix?

**Comment by maria-korosteleva** [comment]
Hi!
Please update your environmental variables as described in the [Installtion doc](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/docs/Installation.md)

**Comment by skeras** [comment]
Hi,
   Thanks for your quick reply.
    Can I run this project on Ubuntu system?

**Comment by maria-korosteleva** [comment]
I was using it on Windows. If you will be able to install Autodesk Maya on Ubuntu, I believe it should also work =)
