### ISSUE TITLE
Mapping between mesh vertices and sewing pattern

### ISSUE THREAD

**Issue by liren2515** [maria-korosteleva/Garment-Pattern-Generator#6]
Hello Maria,

Thanks for your great work! It's very impressive.

I have a question about the mapping mesh vertices and sewing pattern. I'm quite new in this field, so not sure whether this is a stupid question. In the dataset we have the mesh obj files with vertices and faces. And I can find the sewing pattern from pattern.png. Is there a mapping function that can help me map the 3D vertices to 2D pattern?

**Comment by maria-korosteleva** [comment]
Hi Ren!

Thank you very much for the praise and your interest in your work =) 

This is a perfectly valid question! With our data we provide segmentation maps (see *_segmentation.txt in each datapoint folder). For each vertex of the corresponding mesh (line # = vertex id in the mesh), the segmentation mask provides the name of the panel it belongs to, with stitch vertices marked separately.

If you have set up the Maya Environment, you can visualize segmentation labels in Maya with [this script](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/utility%20scripts/maya_segmentaion_viz.py). This is also a good reference for how to load the segmentation labels

Hope this helps =)

**Comment by liren2515** [comment]
Thanks for your quick response!

Sorry, I didn't make myself clear. The sewing pattern can be regarded as a 2D image, right? What I want to know is how to map the 3D vertices to 2D pixel positions. I want to transfer the faces of 3D mesh to the 2D pattern.

**Comment by maria-korosteleva** [comment]
No, we do not represent 2D patterns as images. We represent a sewing pattern as a structured 3D object (provided in JSON format), and each mesh is generated directly from curves that describe pattern's panels. 
Svg and png images of pattern are provided only for visualization / reference purposes 😅

One way of getting the face breakdown of panels while they are flat is to get the geometry when the pattern is loaded into Maya but before initializing the simulation. It looks like this: 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6837635/207076723-3e2ffc7e-1bd7-4610-a3cc-a4127f294ea0.png">.  

Unfortunately, we didn't include that representation with the data, as our related projects have not required that. However, adding this representation to the pipeline should be rather straightforward. If you decide to do that, I'd be happy to answer any other questions you might have in the process

**Comment by liren2515** [comment]
Hello Maria, I have another question for you.

There are 3 body models under `/data_generation/Bodies `. It seems [f_smpl_template_headphones.obj](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/Bodies/f_smpl_template_headphones.obj) is used for the simulation. But this obj is not the original smpl obj, since it is much larger. Could you tell me how to get `f_smpl_template_headphones.obj` from the original smpl body? I need to put the garment on the original body.

**Comment by maria-korosteleva** [comment]
Hi @liren2515, 
Sure. The primary body model we used in the simulation is [f_smpl_template.obj](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/Bodies/f_smpl_template.obj). It's the default SMPL model, but the units are scaled to cm (vertex coordinates x100) for simulation stability. The model center (average of the vertices) is aligned with the world origin. You can scale the final simulated garments down by 100 to get the fitted on the original SMPL body model

[f_smpl_template_headphones.obj](https://github.com/maria-korosteleva/Garment-Pattern-Generator/blob/master/data_generation/Bodies/f_smpl_template_headphones.obj) additionally has ellipsoid objects around ears to prevent the hoods in garments getting tangled in the low-res ear geometry. In our datasets, this model is only used in garments that have hoods

**Comment by maria-korosteleva** [comment]
> No, we do not represent 2D patterns as images. We represent a sewing pattern as a structured 3D object (provided in JSON format), and each mesh is generated directly from curves that describe pattern's panels. Svg and png images of pattern are provided only for visualization / reference purposes 😅

This might be late for the author of the question, but for those facing the same question, I would like to correct myself here. All the 3D meshes in the dataset and any meshes produced by the generation pipeline have texture coordinates (UVs) grouped by individual panels (saved in the obj files). Hence, UVs can be used to recover the mapping between a final 3D model and a flat panel mesh.
