### ISSUE TITLE
_control_to_relative_coord

### ISSUE THREAD

**Issue by Mamba-ZJP** [maria-korosteleva/Garment-Pattern-Generator#9]
Hi maria,

It seems that control scale should be caculated in this way: `control_scale[1] *= np.sign(np.cross(edge_vec, control_vec))` ?

**Comment by maria-korosteleva** [comment]
Hi @Mamba-ZJP 
You are correct, thank you for catching it! Please, submit a PR with this fix, and I will approve right away

**Comment by Mamba-ZJP** [comment]
Ok. I will submit it soon.

**Comment by maria-korosteleva** [comment]
Fixed by https://github.com/maria-korosteleva/Garment-Pattern-Generator/pull/10
